### ISSUE TITLE
DISTINCT in Aggregating functions

### ISSUE THREAD

**Issue by MacondoExpress** [neo4j/cypher-builder#239]
Is currently missing the support for DISTINCT in Aggregating functions.

For instance the following:
`
RETURN collect(DISTINCT this { .id }) AS data
`
or
`
RETURN count(DISTINCT this { .id }) AS data
`
Are valid Cypher.
Reference: https://neo4j.com/docs/cypher-manual/current/functions/aggregating/#_counting_with_and_without_duplicates

**Comment by angrykoala** [comment]
Aggregation functions already support `DISTINCT` (although it is not yet documented):

The following js should generate something similar to what you need
```
Cypher.collect(new Cypher.Node()).distinct();
```
