### ISSUE TITLE
Use logical "&" for label matching in patterns

### ISSUE THREAD

**Issue by jroith** [neo4j/cypher-builder#248]
I have the need to use "&" to combine labels instead of ":" because I am using "&" and "|" elsewhere in the query and neo4j only permits ":" if the logical operators are used nowhere. Furthermore I want to be able to pass in a LabelExpr to HasLabel.

I have a patch to implement this and control it using a parameter, but I'm wondering if there is any performance drawback to modifying the library to just always use the logical notation. It doesn't seem so. If not, would you consider switching to the logical notation everywhere to avoid the flag?

In either case, I'm happy to provide a patch and get one of the changes upstream.

**Comment by angrykoala** [comment]
Hi @jroith 
Just to make sure we are talking of the same thing, could I see a few examples of the js code proposed and the resulting Cypher (actual vs expected)?

Also, I think passing a LabelExpr to hasLabel makes sense, but maybe could we discuss as a separate issue?

**Comment by jroith** [comment]
The intended effect is that I can generate `MATCH(this) WHERE this:Foo&Bar` instead of  `MATCH(this) WHERE this:Foo:Bar` and in the case of expression that I can generate  `MATCH(this) WHERE this:((Complex:Thing)|(Foo&Bar))`

It would be something like this:

```
export class HasLabel extends CypherASTNode {
    private node: NodeRef;
    private expectedLabels: string[] | LabelExpr;
    private useLogicalNotation: boolean;

    /**
     * @hidden
     */
    constructor(node: NodeRef, expectedLabels: string[] | LabelExpr, useLogicalNotation = false) {
        super();
        if (Array.isArray(expectedLabels) && expectedLabels.length === 0)
            throw new Error("HasLabel needs at least 1 label");
        this.node = node;
        this.expectedLabels = expectedLabels;
        this.useLogicalNotation = useLogicalNotation;
    }

    /** @internal */
    public getCypher(env: CypherEnvironment): string {
        const nodeId = this.node.getCypher(env);
        if (Array.isArray(this.expectedLabels)) {
            const labelsStr = this.expectedLabels
                .map((label) => {
                    return escapeLabel(label);
                })
                .join(this.useLogicalNotation ? "&" : ":");
            return `${nodeId}:${labelsStr}`;
        }
        return `${nodeId}:${this.expectedLabels.getCypher(env)}`;
    }
}
```


Additionally I have added on NodeRef:

```

    public hasLabels(...labels: string[]): HasLabel {
        return new HasLabel(this, labels);
    }

    public hasLabelsOf(labels: string[] | LabelExpr, useLogicalNotation = false): HasLabel {
        return new HasLabel(this, labels, useLogicalNotation);
    }

    public hasLabel(label: string, useLogicalNotation = false): HasLabel {
        return new HasLabel(this, [label], useLogicalNotation);
    }


```

**Comment by jroith** [comment]
I currently think that this could be a centralised configuration option and it usually doesn't make sense to configure it individually because almost always it has to be consistent across the query.

The Pattern class has to be adapted as well, so I have now both switched over to "&". So far this seems to work fine with Neo4j 5. Perhaps an idea would be to make it a flag that could be enabled by the GraphQL library or not. Or just to always make it "&" ...

**Comment by angrykoala** [comment]
Hi @jroith 
Using & always is a no-go at the moment, as it is not supported in Neo4j 4
A configuration flag is also possible, but I'd like to avoid that if possible as it adds complexity to using the library

For what you mention, adding a labelExpr to `hasLabel` should be enough to solve your case, as label expressions are already supported on the patterns right?

**Comment by angrykoala** [comment]
The PR #251 covers adding labelExpr to hasLabel which should solve this issue

**Comment by jroith** [comment]
Hi @angrykoala ,

Basically, since I'm inserting the label expression into a query of the GraphQL library, and since neo4j prevents mixing I need to also change the behaviour everywhere neo4j GraphQL calls the builder.
So if there's no flag I need to maintain a fork of the builder for now on top of a neo4j GraphQL fork. Not optimal.

**Comment by angrykoala** [comment]
mmm, ok, I see your point a bit better now

A query such as
```
MATCH(m:Movie:Book)
WHERE m:Book&Movie
RETURN m
```

will not work, so composing a label expression on a bigger query is problematic

This would require a global setting to switch to label expression notation would that be all that is needed to solve your problem?

**Comment by jroith** [comment]
Exactly, a global switch that would ensure that your example comes out as:

```
MATCH(m:Movie&Book)
WHERE m:Book&Movie
RETURN m
```

would solve this.

**Comment by angrykoala** [comment]
Hi @jroith 
I've been playing around with options to solve this (#271) but I think it won't solve your underlying problem

Cypher Builder already supports using `&` instead of `:` by passing a `LabelExpr` instead of an array. It makes sense to add a flag to the `build` method to change the behaviour of the array to make it compatible, which is what my PR does, however, I think that this won't solve your problem, as the `@neo4j/graphql` library will still be generating the Cypher without this flag. If you need support for custom Cypher in graphql using label expressions along with the `@neo4j/graphql` library, I'd recommend you open an issue in that repository, as it needs some changes in how the `cypher-builder` is used by the library

Note that a pure global flag is a no-go, as it would break simultaneous support for Neo4j 4 and Neo4j 5 when using the library

**Comment by jroith** [comment]
@angrykoala If I can enable this labelOperator in the neo4j graphql library then maybe it would solve it? I am already maintaining a local fork of the neo4j graphql library due to some performance optimizations that I think have no hope of getting merged.

**Comment by angrykoala** [comment]
Fair, the next release will contain the option.

The change required would be to add the following to the `.build` method:

```
.build(
    undefined,
    {},
    {
        labelOperator: "&",
    }
);
```

Note that this configuration is a bit of a patch to allow for this behaviour, and will probably change in the next major release of the Cypher Builder for a proper configuration object in the build method (which will be breaking)


Also, I've checked on the `@neo4j/graphql` repo and I couldn't see an issue for the performance optimisations that you mention. Would it be possible to share what the problems leading to the optimizations are?

I cannot guarantee a PR with optimizations can get merged easily (although if you open it we will review and consider it) but an issue detailing the performance problem that prompted the fork would be helpful, as we have a continuous effort to improve the performance of the library

**Comment by jroith** [comment]
@angrykoala I will eventually push these to a fork on GitHub for discussion. However I think they are too controversial to merge, won't work for any schema (a helper field is needed), and also my implementation is problematic - it's an inefficient but simple and robust implementation. Essentially the changes address the problem of the conditional branches that are created when drilling down into fields that are backed by an interface. This is done by adapting the generated cypher of the UNION branches to be identical if possible and then collapsing those cases into a single case. Something similar is done to simplify filtering.

For our queries the query planning time is often reduced from 5 seconds to 100ms and the execution time is usually improved as well. Because the implementation is inefficient, the query generation time in the library is somewhat increased. This could be fixed with a more thoughtful implementation perhaps.

But maybe it can serve as an inspiration for a future improvement in the library.

**Comment by angrykoala** [comment]
Yeah, it sounds like a great place to add some improvements, Any chance you could share the problematic GraphQL  queries in an issue? Maybe we cannot get the same improvements without your changes but still improve a bit those areas
