### ISSUE TITLE
It's not possible to manage node labels using .set() and .remove()

### ISSUE THREAD

**Issue by aureliomarcoag** [neo4j/cypher-builder#401]
Hello! Thanks for all the work on this library, we're using it extensively in our project.

It's currently possible to use `Cypher.Match().set()` to set specific node properties:
```typescript
import Cypher, { SetParam } from "@neo4j/cypher-builder";

const node = new Cypher.Node();
const pattern = new Cypher.Pattern(node, {labels: "oldlabel"})
const setParam : SetParam = [new Cypher.Property(node, "propertyname"), new Cypher.Literal("value")]
const match = new Cypher.Match(pattern).set(setParam)
console.log(match.build())

/*
{
  cypher: "MATCH (this0:oldlabel)\nSET\n    this0.propertyname = \"value\"",
  params: {},
}
*/
```

However, it doesn't seem to be possible to add labels to a node using `set()`, due to the restrictions on the `SetParam` type - it expects an array with two elements where the first *must* be a `PropertyRef`, and the second, its value. When the query is built, the array elements are separated by an equals sign to assign the value to the property. Yet, setting a label would only require a variable reference to the node and the label value (prefixed with `:`), as in the following query:
```cypher
MATCH (this0:oldlabel) SET this0 :newlabel
```

It'd be nice if we could do something like this:
```typescript
import Cypher, { SetParam, LabelParam } from "@neo4j/cypher-builder";

const node = new Cypher.Node();
const pattern = new Cypher.Pattern(node, {labels: "oldlabel"})
const setParam : SetParam = new Cypher.LabelParam(node, "newlabel") // FIXME: "LabelParam"? not sure what the type here should be
const match = new Cypher.Match(pattern).set(setParam)
console.log(match.build())

/*
{
  cypher: "MATCH (this0:oldlabel)\nSET\n    this0 :newlabel,
  params: {},
}
*/
```

As per the title, the same applies to using `new Match().remove()` - it can't be used to remove node labels, only properties.

**Comment by angrykoala** [comment]
Hi @aureliomarcoag 

Yes, indeed adding/removing labels are some use cases that I didn't consider on `SET` and `REMOVE`. Following on your example, I'm thinking on something a bit like:

```js
  const movie = new Cypher.Node();
  const clause = new Cypher.Match(new Cypher.Pattern(movie)).set([
      movie, Cypher.Label("NewLabel")
  ]);
```

```cypher
MATCH(this)
SET this:NewLabel
```

Alternatively, a plain string for the label would also be possible, but I feel it may feel confusing, as nowhere in the API is clear that `"NewLabel"` is a label:

```js
  const clause = new Cypher.Match(new Cypher.Pattern(movie)).set([
      movie, "NewLabel"
  ]);
```

Ideally, this should also allow for a nested array:

```js
  const clause = new Cypher.Match(new Cypher.Pattern(movie)).set([
      movie, [Cypher.Label("L1"), Cypher.Label("L2")]
  ]);
```

To set multiple labels:

```cypher
SET this:L1, this:L2
```

Another option would be to explicitly add the method `setLabel` (similar to how `hasLabel` translates to `m:Movie`)

For `Remove` whatever approach is taken for `SET` should be replicated


Any thoughts on this? Your approach of `LabelParam` would also work although I'm not sure about the ergonomics of that type, naming is tricky for that type, and considering other set options work as pairs of elements, it may be jarring having a labelParam alone:  `.set([prop1, literal1], labelParam)`

**Comment by aureliomarcoag** [comment]
Hey @angrykoala!
> Your approach of LabelParam would also work although I'm not sure about the ergonomics of that type, naming is tricky for that type, and considering other set options work as pairs of elements, it may be jarring having a labelParam alone

I agree - best support this in a way similar to how properties work. I would also prefer the label string to be wrapped in a type that encodes its meaning (like `Cypher.Literal` does) rather than just using a string. Supporting an array also makes sense to me, as it could map to the following Cypher query:

```cypher
MATCH (movie:movie) SET movie:L1:L2
```

Hence, I think your example works really well:
```typescript
  const movie = new Cypher.Node();
  const clause = new Cypher.Match(new Cypher.Pattern(movie)).set([
      movie, [Cypher.Label("L1"), Cypher.Label("L2")]
  ]);
```

Thanks!

**Comment by angrykoala** [comment]
Chatting with @MacondoExpress 
He proposed the following alternative:

```js
const movie = new Cypher.Node();
const clause = new Cypher.Match(new Cypher.Pattern(movie)).set([
    movie.label("NewLabel")
]);
```

This alternative would be in line with the method `hasLabel`
