### ISSUE TITLE
Creating relationship with existing nodes

### ISSUE THREAD

**Issue by Eclegv** [neo4j/cypher-builder#88]
### Question

How do you create a relationship between two already existing nodes ?

### Expected behavior

Being able to generate this query, as seen in : https://neo4j.com/docs/cypher-manual/current/clauses/create/ in the section create relationship

```cypher
MATCH
  (a:X),
  (b:Y)
WHERE a.name = 'A' AND b.name = 'B'
CREATE (a)-[r:RELTYPE]->(b)
RETURN type(r)
```

### Actual behavior

I'm only able to generate this query :

```cypher
MATCH (this0:Rpg)
MATCH (this1:User)
WHERE (this1.id = $param0 AND this0.id = $param1)
CREATE (this1:User)-[this2:IS_IN_RPG { role: $param2 }]->(this0:Rpg)
RETURN this1, this0
```

which try to create the nodes and relationship instead of the relationship

### Screenshots 

![image](https://github.com/neo4j/cypher-builder/assets/11862064/06f67662-8492-4e8e-9579-74fbbac4d313)

### Environment

- cypher-builder : 1.1.2

**Comment by angrykoala** [comment]
Hi @Eclegv 

I understand that the problem with this query is that 
```cypher
CREATE (this1:User)-[this2:IS_IN_RPG { role: $param2 }]->(this0:Rpg)
``` 
contains the labels and the expected pattern is
```cypher
CREATE (this1)-[this2:IS_IN_RPG { role: $param2 }]->(this0)
```

To remove the labels from the pattern, you can do so with `.withoutLabels()`:

```js
new Cypher.Pattern(USER_NODE).withoutLabels().related(IS_IN_RELATIONSHIP).to(RPG_NODE).withoutLabels()
```

You can find more info at https://neo4j.github.io/cypher-builder/cypher-builder/current/patterns/#_remove_labels_and_types

Would that solve the question?

**Comment by Eclegv** [comment]
Hi @angrykoala 

Yes, it solves the question, sorry I missed this point in the documentation and thank you for your fast answer !

Thank you again for your work on this library !
